### ISSUE TITLE
Fix footer to be completely responsive for mobile devices

### ISSUE THREAD

**Issue by rowmatrix** [rowmatrix/rr-front-end#3]
This website is responsive. However, for small screens the footer is not displayed correctly. Here is what it currently looks like: 
![img_0051](https://cloud.githubusercontent.com/assets/12551294/19017046/ed3ef154-87e1-11e6-997b-cbb63be5f1ac.PNG)
![img_0052](https://cloud.githubusercontent.com/assets/12551294/19017047/f2350842-87e1-11e6-9e91-d5d9826a077b.PNG)

The footer text should be **centered** in both these instances.

**Comment by TruenoElfico** [comment]
i will try it

**Comment by rowmatrix** [comment]
Alright thanks

**Comment by TruenoElfico** [comment]
asign me

**Comment by TruenoElfico** [comment]
![image](https://cloud.githubusercontent.com/assets/14181972/19017586/194ba17e-87fc-11e6-9127-c6819410494e.png)

**Comment by rowmatrix** [comment]
@TruenoElfico That looks great! Is that on a smartphone? I would like to see a pic for landscape and portrait on a smartphone.

**Comment by TruenoElfico** [comment]
![image](https://cloud.githubusercontent.com/assets/14181972/19018137/5d987e44-8813-11e6-919d-0b2fc03bf7a1.png)


I miss-click the merge button to master, but i trust that you will acept it, if not you can rollback in branches.

**Comment by TruenoElfico** [comment]
You need to implement a grid system for future projects, and also look for a .container class example to center in a better way your content.

**Comment by rowmatrix** [comment]
Yes I agree, the code needs to be more modular.

**Comment by TruenoElfico** [comment]
hahahaha nevermind, i just try the revert button. all is fine

**Comment by rowmatrix** [comment]
So in PR 6, all the changes have been made to the footer?

**Comment by TruenoElfico** [comment]
in pr5 are the changes

**Comment by rowmatrix** [comment]
Alright all done! Thanks for your help @TruenoElfico ! Closing issue now
